version: "3"

networks:
  default:
    external:
      name: traefik

services:
  portainer:
    image: portainer/portainer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - ROOT_URL=${ROOT_URL}
      - TZ=${TZ}
    env_file:
      - ./credentials.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
    labels:
      # define auth middleware
      - "traefik.http.middlewares.traefik-auth.basicauth.users=sneaker15:$$2y$$10$$Tv8w.gNaK494ENTLHgO/MefJa/XPldNYEWbSoQo77mcvUkM5RRHeu"
      # define https endpoint
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # define resolver configuration
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.tls.domains[0].main=${ROOT_URL}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.${ROOT_URL}"
      - "traefik.http.routers.traefik.service=api@internal"

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    container_name: whoami
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

volumes:
  portainer_data:
