api:
  dashboard: true
  debug: true

entryPoints:
# TODO: check if both can be merged into one
  # dns:
  #   address: ":53"
  dns-tcp:
    address: ":53/tcp"
  dns-udp:
    address: ":53/udp"
  mqtt:
    address: ":1883/tcp"
  mqtts:
    address: ":8883/tcp"
  tftp:
    address: ":69/udp"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}
  wss:
    address: ":4433"
    http:
      tls: {}

# uncomment for DEBUG message output
# log:
#   level: DEBUG

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    # defaultRule: 'Host(`{{ normalize .Name }}`)'
    # defaultRule: 'Host(`{{ normalize .Name }}.{{env "ROOT_URL"}}`)'
    defaultRule: 'Host(`{{ index .Labels "com.docker.compose.service"}}.{{env "ROOT_URL"}}`)'

certificatesResolvers:
  cloudflare:
    acme:
      # uncomment to test against letsencrypt staging
      # caserver: https://acme-staging-v02.api.letsencrypt.org/directory
      email: letsencrypt@outgoer.de
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
